# Generated by Django 4.2.7 on 2024-02-01 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='Age',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dogs',
            name='date_registered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
